
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

int sum = 0;

int limited_fibo( int a, int b, int limit)
{
	int c = a + b;
	if ( c > limit) return 0;

	cout << "c=" << c << endl;

	if( c%2 == 0) sum += c;
	return limited_fibo( b, c, limit);
}

int main(int argc, char** argv)
{
	limited_fibo( 1, 1, 400 * 10000);
	std::cout << "sum=" << sum << std::endl;
	return 0;
}
